config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "users/registrations" }

  resources :users, only: [:index, :destroy, :show] do
    member do
      get "promote"
      get "demote"
      get "inspect"
      get "categories"
      get "events"
    end
  end

  # General page routes
  get "/home" => "home#index", :as => :home
  get "/userviewer" => "pages#userviewer"
  get "/about" => "pages#about"
  get "/status" => "pages#status"

  # Follow Routes
  resources :relationships

  # Group Routes
  resources :groups
  resources :user_groups, only: [:create, :update, :destroy]
  post "/invite_to_group", to: "user_groups#invite_to_group", as: :invite_to_group
  get "join_group/:id", to: "groups#join", as: :join_group
  get "leave_group/:id", to: "groups#leave", as: :leave_group

  # Admin Routes
  get "/sandbox" => "pages#sandbox"
  get "/admin" => "pages#admin", :as => :admin_panel
  post "/run_command" => "pages#run_command"
  post "/check_if_command_is_finished" => "pages#check_if_command_is_finished"

  # User Routes
  post "/deny_friend" => "friendships#deny"
  post "/confirm_friend" => "friendships#confirm"

  # Event Invite Routes
  get "/event-invite/:id/email-action/:new_status", to: "event_invites#email_action", as: :event_invite_email_action

  # Event backend commands
  resources :events, only: [:destroy] do
    post :setup_hosting, on: :member
    resources :event_invites, only: [:create], as: :invites
  end

  resources :event_invites, only: [:destroy]
  resources :categories, only: [:create, :update, :destroy]
  resources :repeat_exceptions, only: [:create, :update, :destroy]

  resource :schedule, only: [:show] do
    post :save
    get "/beta", to: "schedules#show_beta"
  end

  resources :notifications, only: [:destroy] do
    post "update(/:response)", to: "notifications#updated", as: :update, on: :member
    post :read, on: :collection
  end

  resource :search, only: [] do
    get :all, :users, :group_invitable_users
  end

  root "home#index"
end

app/models/notification.rb
class Notification < ApplicationRecord
  # Events define the types of notifications. DO NOT CHANGE EXISTING EVENTS
  enum event: { system_message: 0, follow_request: 1, user_message: 2, group_invite: 3,
                group_invite_request: 4, event_invite: 5, event_update: 6 }

  belongs_to :entity, polymorphic: true, optional: true

  belongs_to :sender, class_name: "User", foreign_key: "sender_id",
                      optional: true, default: -> { Current.user }

  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"

  scope :unread, -> { where(viewed: false) }

  validates :event, uniqueness: {
    scope: [:receiver_id, :sender_id, :entity_id, :message],
    message: "This notification already exists"
  }

  def self.send_event_invite(invite)
    Notification.create(
      receiver: invite.user,
      event: :event_invite,
      entity: invite
    )
  end

  def self.send_event_update(user, event)
    Notification.create(
      receiver: user,
      event: :event_update,
      entity: event,
      message: "The event \"#{event.name}\" has been updated. Review the event in your schedule."
    )
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def read
    @notifications = current_user.notifications
    @notifications.update_all viewed: true
    render plain: ""
  end

  # Notification responses/updates are routed through here.
  def updated
    @notification = Notification.find(params[:id])

    # dispatches call to private method (if implemented)
    send(@notification.event) if respond_to?(@notification.event, true)

    @notification.destroy
    render json: {}, status: :ok
  end

  def destroy
    notif = Notification.find(params[:id])
    notif.destroy
    render plain: "hurrah"
  end

  private

  def follow_request
    relationship = @notification.entity

    if params[:response] == "confirm"
      relationship.update(confirmed: true)
    elsif params[:response] == "deny"
      relationship.destroy
    end
  end

  def group_invite
    group = @notification.entity
    group.add(current_user) if params[:response] == "accepted"
  end

  def group_invite_request
    group = @notification.entity

    return unless params[:response] == "accepted"

    group.add(@notification.sender)

    Notification.create!(
      receiver: @notification.sender,
      message: "You're now a member of #{group.name}!"
    )
  end

  def event_invite
    invite = @notification.entity

    case params[:response]
    when "accepted" then invite.accept!
    when "maybe" then invite.maybe!
    when "declined" then invite.decline!
    else raise "invalid response: #{params[:response]}"
    end
  end
end

app/views/notifications/_event_invite.html.erb
<% invite = notification.entity %>

<div class="notif event-invite">
  <div class="context">
    <%= link_avatar invite.user %>
    <p><%= link_to invite.sender.name, invite.sender %> invited you to the event '<%= invite.host_event.name %>'</p>
  </div>

  <div class="choices">
    <%= link_to "I'm attending", update_notification_path(notification, "accepted"), method: :post, remote: true, class: "green button" %>
    <%= link_to "Maybe", update_notification_path(notification, "maybe"), method: :post, remote: true, class: "button" %>
    <%= link_to "No, thanks", update_notification_path(notification, "declined"), method: :post, remote: true, class: "red button" %>
  </div>
</div>

app/views/notifications/_event_update.html.erb
<div class="notif general">
  <div><%= notification.message %></div>
  <%= link_to "OK", update_notification_path(notification), method: :post, remote: true %>
</div>

app/views/notifications/_follow_request.html.erb
<div class="notif follow-request">
  <%= link_avatar notification.sender, size: 90 %>
  <span class="message"><%= notification.sender.name %></span>

  <%= link_to "", update_notification_path(notification, "confirm"), method: :post, remote: true, class: "confirm" %>
  <%= link_to "", update_notification_path(notification, "deny"), method: :post, remote: true, class: "deny" %>
</div>

app/views/notifications/_group_invite.erb
<% group = notification.entity %>

<div class="notif group-invite">
  <%= link_avatar group, size: 90 %>
  <span class="message"><%= group.name %></span>

  <%= link_to "", update_notification_path(notification, "accepted"), method: :post, remote: true, class: "confirm" %>
  <%= link_to "", update_notification_path(notification, "denied"), method: :post, remote: true, class: "deny" %>
</div>

app/views/notifications/_group_invite_request.erb
<% group = notification.entity %>

<div class="notif group-invite">
  <%= link_avatar notification.sender, size: 90 %>
  <span class="message"><%= notification.sender.name %> would like to join <%= group.name %></span>

  <%= link_to "", update_notification_path(notification, "accepted"), method: :post, remote: true, class: "confirm" %>
  <%= link_to "", update_notification_path(notification, "denied"), method: :post, remote: true, class: "deny" %>
</div>

app/views/notifications/_notification.html.erb
<%= render partial: "/notifications/#{notification.event}",
           locals: { notification: notification } %>

app/views/notifications/_system_message.html.erb
<div class="notif general">
  <div><%= notification.message %></div>
  <%= link_to "OK", update_notification_path(notification), method: :post, remote: true %>
</div>

app/views/notifications/_user_message.html.erb
<div class="notif general">
  <%= link_to(notification.sender) do %>
    <div id="user-avatar">
      <img src="<%= notification.sender.user_avatar(90) %>">
    </div>
  <% end %>

  <div><%= notification.sender.name %> <%= notification.message %></div>
</div>