config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "users/registrations" }

  resources :users, only: [:index, :destroy, :show] do
    member do
      get "promote"
      get "demote"
      get "inspect"
      get "categories"
      get "events"
    end
  end

  # General page routes
  get "/home" => "home#index", :as => :home
  get "/userviewer" => "pages#userviewer"
  get "/about" => "pages#about"
  get "/status" => "pages#status"

  # Follow Routes
  resources :relationships

  # Group Routes
  resources :groups
  resources :user_groups, only: [:create, :update, :destroy]
  post "/invite_to_group", to: "user_groups#invite_to_group", as: :invite_to_group
  get "join_group/:id", to: "groups#join", as: :join_group
  get "leave_group/:id", to: "groups#leave", as: :leave_group

  # Admin Routes
  get "/sandbox" => "pages#sandbox"
  get "/admin" => "pages#admin", :as => :admin_panel
  post "/run_command" => "pages#run_command"
  post "/check_if_command_is_finished" => "pages#check_if_command_is_finished"

  # User Routes
  post "/deny_friend" => "friendships#deny"
  post "/confirm_friend" => "friendships#confirm"

  # Event Invite Routes
  get "/event-invite/:id/email-action/:new_status", to: "event_invites#email_action", as: :event_invite_email_action

  # Event backend commands
  resources :events, only: [:destroy] do
    post :setup_hosting, on: :member
    resources :event_invites, only: [:create], as: :invites
  end

  resources :event_invites, only: [:destroy]
  resources :categories, only: [:create, :update, :destroy]
  resources :repeat_exceptions, only: [:create, :update, :destroy]

  resource :schedule, only: [:show] do
    post :save
    get "/beta", to: "schedules#show_beta"
  end

  resources :notifications, only: [:destroy] do
    post "update(/:response)", to: "notifications#updated", as: :update, on: :member
    post :read, on: :collection
  end

  resource :search, only: [] do
    get :all, :users, :group_invitable_users
  end

  root "home#index"
end

app/models/group.rb
class Group < ApplicationRecord
  include Profile

  enum privacy: { public_group: 0, private_group: 1, secret_group: 2 }

  has_many :users_groups, dependent: :destroy
  has_many :users, -> { where users_groups: { accepted: true } }, through: :users_groups
  alias_attribute :members, :users

  has_many :categories, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :repeat_exceptions, dependent: :destroy
  has_many :notifications, as: :entity, dependent: :destroy

  validates_presence_of :name

  # Returns true if the group has a non-default avatar, false otherwise.
  def has_avatar?
    avatar.exists?
  end

  # Returns a url to the avatar with the width in pixels.
  def avatar_url(size = 256)
    return avatar.url(size <= 60 ? :thumb : :profile) if has_avatar? # uploaded avatar

    gravatar_url(size) # default avatar
  end

  # Returns the role of user in this group (e.g. 'admin') or
  # nil if the user isn't even a member of this group.
  def role(user)
    UsersGroup.find_by(user_id: user.id, group_id: id, accepted: true)&.role&.to_sym
  end

  def invited?(user)
    invitation_for(user).exists?
  end

  def members_with_role(role)
    User.where(id: UsersGroup.where(group_id: id, accepted: true, role: role).select(:user_id))
  end

  def member?(user)
    members.include?(user)
  end

  def empty?
    members.empty?
  end

  def size
    members.size
  end

  def add(user, role: :member)
    UsersGroup.create group_id: id, user_id: user.id, accepted: true, role: role
  end

  def membership(user)
    return nil if user.nil?

    UsersGroup.find_by group_id: id, user_id: user.id
  end

  def owner
    User.find_by(id: UsersGroup.where(group_id: id, role: :owner).select(:user_id))
  end

  def pending_invite_request?(user)
    # optimization: invite requests are only necessary for private and secret groups
    return false if public_group?

    Notification.exists?(event: :group_invite_request, sender: user, entity: self)
  end

  def invitation_for(user)
    Notification.find_by(event: :group_invite, receiver: user, entity: self)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authorize_signed_in!, except: [:show]

  def index
    @joinable_groups = Group.where(privacy: :public_group)
                            .where.not(id: current_user.groups)
                            .page(params[:page]).per(25)
                            .eager_load(:users).references(:users_groups)

    paginate(@joinable_groups, "large_group_card")
  end

  def show
    @group = Group.from_param(params[:id])

    # forces custom urls to be displayed (when applicable)
    redirect_to group_path(@group), status: :moved_permanently if params[:id].is_int? && @group.has_custom_url?

    @view = params[:view]&.to_sym || :overview
    @membership = @group.membership(current_user)
    authorize! :show, @group

    case @view
    when :manage_members
      authorize! :manage_members, @group
      @members = @group.users_groups
    when :members
      @members = UsersGroup.where(group: @group, accepted: true).page(params[:page]).per(25)
    when :overview
      categories = @group.categories.select { |cat| cat.accessible_by? current_user }
      events = @group.events.select { |event| event.accessible_by? current_user }

      @upcoming_events = visible_upcoming_events
      @activities = (@group.members + categories + events)
                    .sort_by(&:created_at).reverse.first(2)
    when :schedule
      @read_only = cannot? :edit_schedule, @group
    end
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.from_param(params[:id])
    @role = @group.role(current_user)
    authorize! :update, @group
  end

  def create
    @group = Group.new group_create_params

    if @group.save
      @group.add(current_user, role: :owner)
      redirect_to @group, notice: "Group was successfully created."
    else
      render :new
    end
  end

  def update
    @group = Group.from_param(params[:id])
    authorize! :update, @group

    if @group.update group_create_params
      redirect_to @group, notice: "Group was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @group = Group.from_param(params[:id])
    authorize! :destroy, @group

    if @group.destroy
      redirect_to groups_url, notice: "Group was successfully destroyed."
    else
      redirect_to request.referrer, alert: "Couldn't destroy group"
    end
  end

  def join
    @group = Group.from_param(params[:id])
    @user = current_user

    if @group.public_group?
      @group.add(@user)
      @group.invitation_for(@user)&.destroy # remove outstanding invitations
    elsif @group.private_group?
      Notification.create(sender: current_user, receiver: @group.owner,
                          event: :group_invite_request, entity: @group)
    end

    redirect_to request.referrer
  end

  def leave
    group = Group.from_param(params[:id])
    old_role = group.role(current_user)
    membership = UsersGroup.find_by(group: group, user: current_user, accepted: true)

    if membership
      membership.destroy

      if group.empty?
        group.destroy
      elsif old_role == :owner
        # looks like you're today's winner!
        UsersGroup.where(group: group, accepted: true).where.not(user: current_user)
                  .first.update(role: :owner)
      end

    else
      redirect_to request.referrer, alert: "You can't leave a group you are not in!"
      return
    end

    redirect_to groups_path
  end

  protected

  # 'edit' and 'new' will redirect back to the group modified
  def after_update_path_for(resource)
    group_path resource
  end

  private

  def group_create_params
    params.require(:group)
          .permit(:name, :description, :avatar, :banner,
                  :posts_preapproved, :custom_url, :privacy)
  end

  def visible_upcoming_events
    @group.upcoming_events(current_user&.home_time_zone || "Central Time (US & Canada)")
          .select { |event| event.accessible_by?(current_user) }
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  # returns an array of symbols indicating what roles the current user
  # can assign a group member (UserGroup) to
  def assignable_roles(membership)
    available_roles = UsersGroup.roles.keys.select do |to_role|
      (can? :update, membership, to_role) && (to_role != membership.role)
    end

    available_roles.sort_by { |role| UsersGroup.role_priority(role) }
  end

  def leave_warning(user_group)
    return nil unless user_group.owner?

    if user_group.group.size == 1
      "Are you sure? The group will be disbanded."
    else
      "Are you sure? Someone else in the group will become the new owner."
    end
  end

  def role_assign_confirmation(role)
    return nil unless role.to_sym == :owner

    "Are you sure? You will be demoted to a moderator."
  end

  def remove_confirmation(user_group)
    "You want to kick yourself? #{leave_warning user_group}" if user_group.user == current_user
  end
end

app/views/groups/_basic_user_block.erb
<% user_group = basic_user_block %>

<div class="basic-member-block user-listing grey-box">
  <%= link_avatar user_group.user %>

  <div class="user-details">
    <span class="name"><%= user_group.user.name %></span><br>
    <span class="role"><%= user_group.role.titleize %></span>
  </div>
</div>

app/views/groups/_form.html.erb
<%
  # e.g. [[Public, PUBLIC], [Private, PRIVATE], ...]
  group_privacy_options = Group.privacies.keys.map { |opt| [opt.titleize, opt] }
%>

<div class="flex center-horizontal">
  <%= form_for @group, html: { class: "basic" } do |f| %>
    <%= validation_error_messages! @group %>

    <div class="form-group">
      <%= f.label :name, "Name", class: "heading" %>
      <%= f.text_field :name, maxlength: 32, autofocus: true, placeholder: "Pick a group name" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description", class: "heading" %>
      <%= f.text_area :description, :rows => 4, placeholder: "Tell others what your group is about", maxlength: 256 %>
    </div>

    <div class="form-group flex col">
      <%= f.label "Avatar Image", class: "heading" %>

      <% if @group.avatar.exists? %>
        <%= image_tag @group.avatar.url(:profile), class: "avatar-preview" %>
      <% end %>

      <%= f.file_field :avatar, class: "hide", accept: 'image/png,image/gif,image/jpeg' %>
      <%= f.label :avatar, "Upload Image", class: "gray button" %>
    </div>

    <div class="form-group flex col">
      <%= f.label "Banner Image", class: "heading" %>

      <% if @group.banner.exists? %>
        <%= image_tag @group.banner.url(:mobile), class: "banner-preview" %>
      <% end %>

      <%= f.file_field :banner, class: 'hide', accept: 'image/png,image/gif,image/jpeg' %>
      <%= f.label :banner, "Upload Image", class: "gray button" %>
    </div>

    <div class="form-group">
      <%= f.label :custom_url, "Custom Url", class: "heading" %>
      <%= f.text_field :custom_url %>
    </div>

    <%# <div class="form-group"> %>
      <%#= f.check_box :posts_preapproved, title: I18n.t('groups.approved_posting_explanation') %>
      <%#= f.label :posts_preapproved, "Pre-approved posting", class: "heading" %>
    <%# </div> %>

    <div class="form-group">
      <div class="explained-label">
        <%= f.label :privacy, "Group Privacy", class: "heading" %>
        <%= image_tag "question-circle.svg", width: 20, class: "faded question-tooltip", title: I18n.t('groups.group_privacy_explanation') %>
      </div>

      <%= f.select :privacy, group_privacy_options %>
    </div>

    <%= f.submit class: "large button" %>
  <% end %>
</div>

app/views/groups/_large_group_card.erb
<% group = large_group_card %>

<div class="large-group-card grey-box">
  <div class="card-header">
    <% if group.banner.exists? %>
      <div class="banner-img" style="background-image:url(<%= group.banner.url(:mobile) %>);"></div>
    <% else %>
      <div class="banner-img"></div>
    <% end %>

    <%= link_avatar group %>

    <%= link_to group.name, group, class: "normal title" %>

    <% if group.pending_invite_request? current_user %>
      <h3>Invite Request Sent!</h3>
    <% else %>
      <%= link_to "+ Join", join_group_path(group), class: "button -join" %>
    <% end %>
  </div>

  <div class="main">
    <div class="flex-text-img -align-top">
      <%= image_tag "description.svg", alt: "" %>
      <% if group.description.present? # If the description is provided %>
        <%= group.description %>
      <% else %>
        <em>This group has no description.</em>
      <% end %>
    </div>
    <div class="flex-text-img">
      <%= image_tag "person-multiple.png", alt: "" %>
      <%= group.size %> <%= 'Member'.pluralize(group.size) %>
    </div>
  </div>
</div>

app/views/groups/_manage_user_card.erb
<div class="user-with-options">
  <div class="overview">
    <div class="name-and-avatar">
      <%= link_avatar(membership.user) %>
      <h3 class="name"><%= membership.user.name %></h3>
    </div>

    <h4 class="role"><%= membership.role %></h4>
  </div>

  <div class="options" style="display: none">
    <div>
      <% assignable_roles(membership).each do |role| %>
        <%= link_to "Make #{role.humanize}", user_group_path(membership, role: role),
                    data: { confirm: role_assign_confirmation(role) },
                    method: :put, class: "wide hollow orange button" %>
      <% end %>
    </div>

    <div>
      <% if can? :destroy, membership %>
        <%= link_to "Remove", user_group_path(membership),
                    data: { confirm: remove_confirmation(membership) },
                    method: :delete, class: "wide hollow red button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/_small_activity_card.erb
<div class="small-activity-card">
  <% if act.is_a?(User) %>
    <% currusergroup = UsersGroup.find_by(user_id:act.id,group_id: @group); curruser = act.id %>
    <%= link_avatar act %>
    <div class="user-information">
      <div class="user-name"><%= act.name %></div>
      <div class="act-name">Joined</div>
      <div class="time-ago"> <%= relative_time_tag(currusergroup.created_at) %> </div>
    </div>
  <% elsif act.is_a?(Category) %>
    <% curruser = User.find(act.user_id) %>
    <%= link_avatar curruser %>
    <div class="user-information">
      <div class="user-name"><%= curruser.name %></div>
      <div class="act-name"> Created category <%= act.name %> </div>
      <div class="time-ago"> <%= relative_time_tag(act.created_at) %> </div>
    </div>
  <% elsif act.is_a?(Event) %>
    <% curruser = User.find(act.user_id) %>
    <%= link_avatar curruser %>
    <div class="user-information">
      <div class="user-name"><%= curruser.name %></div>
      <div class="act-name"> Created event <%= act.name %></div>
      <div class="time-ago"> <%= relative_time_tag(act.created_at) %> </div>
    </div>
  <% end %>
</div>

app/views/groups/_small_group_card.erb
<div class="small-group-card grey-box">
<%= link_avatar group, size: 64 %>

  <div class="main">
    <%= link_to group.name, group, class: [:normal, :title] %>

    <div class="flex-text-img">
        <%= image_tag "person-multiple.png", alt: "" %>
        <%= group.size %> <%= 'Member'.pluralize(group.size) %>
    </div>
  </div>

  <%# Show edit link if the current_user can edit this group %>
  <% if can? :update, group %>
    <%= link_to edit_group_path(group) do %>
      <%= image_tag "gear.svg", class: "edit-icon", alt: "Gear" %>
    <% end %>
  <% end %>
</div>

app/views/groups/add_users.html.erb
<% content_for :title do %> - Manage Users<% end %>

<div class="page-container">
  <h1 class="zero-bot"><%= link_to(@group.name, group_path(@group)) %></h1>
  <h2 class="page-titler zero-top">Manage Users</h2>
  <h4 class="zero-top">You can add your followers to this group.</h4>
  <% @followers.each do |user| %>
    <%= render "shared/user_box", user: user %>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h1>Group Settings (for <%= @group.name %>)</h1>

<%= render 'form' %>

<%= form_for(@group, url: group_path(@group), :method => :POST, :html => {:class => 'thin'}) do |f| %>
<% end %>

app/views/groups/index.html.erb
<%= stylesheet_link_tag "groups" %>
<%= javascript_include_tag "groups/index" %>
<div class="page-container">
  <h2 class="group-heading flex-text-img left-align">
    <%= image_tag "person-one.svg", alt: "" %>
    Your Groups
  </h2>
  <% if current_user.groups.empty? %>
    <p class="left-align">
      You don't belong to any groups! Join a group and it will show up here.
    </p>
  <% else %>
    <div class="two-col-card-cont">
      <%= render partial: "small_group_card", collection: current_user.groups, as: :group %>
    </div>
  <% end %>

  <div id="groups-list-header">
    <div id="header-info" class="group-heading">
      <h2 class="flex-text-img left-align">
        <%= image_tag "globe.svg", alt: "" %>
        Public Groups
      </h2>
      <%= link_to "+ Create Group", new_group_path, class: "large green button" %>
    </div>

    <p>The groups listed below are all public. Check your notifications for private group invitations.</p>
  </div>

  <% if @joinable_groups.any? %>
    <div id="joinable-groups-list" class="two-col-card-cont">
        <%= render partial: "large_group_card", collection: @joinable_groups %>
    </div>
  <% else %>
    <h4> There are no public groups you don't belong to on Carpe, but that means you can make one! Create a public group and all Carpe users will see it here. </h4>
  <% end %>
</div>

app/views/groups/new.html.erb
<h1>Create Group</h1>

<%= render 'form' %>

app/views/groups/show.html.erb
<%= stylesheet_link_tag "profile" %>
<%= stylesheet_link_tag "groups" %>
<%= javascript_include_tag "groups/show" %>

<div class="profile-header group">
  <% if @group.banner.exists? %>
    <div class="banner-img" style="background-image:url(<%= @group.banner.url(:desktop) %>);"></div>
  <% else %>
    <div class="banner-img"></div>
  <% end %>

  <div class="header-block">
    <div class="dark-background"></div>
    <div class="avatar">
      <%= image_tag @group.avatar_url(200) %>
    </div>

    <div class="profile-name-block">
      <div class="profile-name">
        <span class="profile-name-text"><%= @group.name %></span>
        <% if user_signed_in? %>
          <% if current_user.in_group?(@group) %>
            <%= link_to(leave_group_path(@group), class: "leave button",
                data: { confirm: leave_warning(@membership) }) do %>
                <%= image_tag "leave.svg", alt: "" %>
                Leave Group
            <% end %>

            <%# Show Manage Group link if this user can edit the group %>
            <% if can? :update, @group %>
              <%= link_to edit_group_path(@group), class: "manage button" do %>
                <%= image_tag "gear_darkgray.svg", alt: "" %>
                Manage Group
              <% end %>
            <% end %>
          <% else %>
            <% if @group.pending_invite_request? current_user %>
              <button class="button disabled">Invite Pending</button>
            <% else %>
              <%= link_to "Join Group", join_group_path(@group), class: "green button" %>
            <% end %>
          <% end %>
        <% end %>
      </div>

    <div class="privacy-block">
      <div class="profile-privacy"><%= @group.privacy.titleize %></div>
        <div id="group-profile-buttons">
          <%= link_to group_path(@group, view: :overview) do %>
            <div class="<%= "curr" if @view == :overview %>">Overview</div>
          <% end %>

          <%= link_to group_path(@group, view: :schedule) do %>
            <div class="<%= "curr" if @view == :schedule %>">Schedule</div>
          <% end %>

          <%= link_to group_path(@group, view: :members) do %>
            <div class="<%= "curr" if @view == :members %>">
              <%= pluralize(@group.members.count, "Member") %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="user-invites-overlay-box" class="overlay-box">
  <!--<span class="red close button"></span>-->
  <h3>Invite Members</h3>
  <%= render "shared/user_adder", name: "user_ids", search_path: group_invitable_users_search_path(group_id: @group.id) %>
  <span class="green button" id="group-inviter-send-invite" onclick="sendInvites(this, <%= @group.id %>)">Send Invite</span>
</div>

<%= render "groups/pages/#{@view.to_s}" %>