config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "users/registrations" }

  resources :users, only: [:index, :destroy, :show] do
    member do
      get "promote"
      get "demote"
      get "inspect"
      get "categories"
      get "events"
    end
  end

  # General page routes
  get "/home" => "home#index", :as => :home
  get "/userviewer" => "pages#userviewer"
  get "/about" => "pages#about"
  get "/status" => "pages#status"

  # Follow Routes
  resources :relationships

  # Group Routes
  resources :groups
  resources :user_groups, only: [:create, :update, :destroy]
  post "/invite_to_group", to: "user_groups#invite_to_group", as: :invite_to_group
  get "join_group/:id", to: "groups#join", as: :join_group
  get "leave_group/:id", to: "groups#leave", as: :leave_group

  # Admin Routes
  get "/sandbox" => "pages#sandbox"
  get "/admin" => "pages#admin", :as => :admin_panel
  post "/run_command" => "pages#run_command"
  post "/check_if_command_is_finished" => "pages#check_if_command_is_finished"

  # User Routes
  post "/deny_friend" => "friendships#deny"
  post "/confirm_friend" => "friendships#confirm"

  # Event Invite Routes
  get "/event-invite/:id/email-action/:new_status", to: "event_invites#email_action", as: :event_invite_email_action

  # Event backend commands
  resources :events, only: [:destroy] do
    post :setup_hosting, on: :member
    resources :event_invites, only: [:create], as: :invites
  end

  resources :event_invites, only: [:destroy]
  resources :categories, only: [:create, :update, :destroy]
  resources :repeat_exceptions, only: [:create, :update, :destroy]

  resource :schedule, only: [:show] do
    post :save
    get "/beta", to: "schedules#show_beta"
  end

  resources :notifications, only: [:destroy] do
    post "update(/:response)", to: "notifications#updated", as: :update, on: :member
    post :read, on: :collection
  end

  resource :search, only: [] do
    get :all, :users, :group_invitable_users
  end

  root "home#index"
end

app/models/user.rb
# The User model, which defines a unique user and all of the properties they have
class User < ApplicationRecord
  include Profile

  has_many :active_relationships,  class_name: "Relationship",
                                   foreign_key: "follower_id",
                                   dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy

  has_many :all_following, through: :active_relationships,  source: :followed # all followers, including pending
  has_many :all_followers, through: :passive_relationships, source: :follower # all followers, including pending

  has_many :users_groups, dependent: :destroy
  has_many :groups, -> { where users_groups: { accepted: true } }, through: :users_groups
  has_many :notifications, class_name: "Notification", foreign_key: "receiver_id"

  has_many :event_invites_received, class_name: "EventInvite",
                                    foreign_key: :user_id,
                                    dependent: :destroy

  has_many :event_invites_sent, class_name: "EventInvite",
                                foreign_key: "sender_id"

  has_many :events_invited_to, through: :event_invites_received,
                               source: :host_event

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  devise :omniauthable
  validates_presence_of :name, :home_time_zone

  # when group_id is used, user_id represents the creator of a
  # category/event/exception (as opposed to its owner)
  has_many :categories, -> { where group_id: nil }
  has_many :events, -> { where group_id: nil }
  has_many :repeat_exceptions, -> { where group_id: nil }

  belongs_to :default_event_invite_category, class_name: "Category", optional: true

  def send_signup_email
    UserNotifier.send_signup_email(self).deliver_now
  end

  after_create :send_signup_email

  ##########################
  ##### EVENT METHODS ######
  ##########################

  # return events that are currently going on
  def current_events
    events_in_range(1.day.ago, Time.current, home_time_zone)
      .select(&:current?).sort_by(&:end_date)
  end

  # returns the next upcoming event within the next day
  def next_event
    events_in_range(Time.current, 1.day.from_now, home_time_zone)
      .min_by(&:date)
  end

  # returns whether the user is currently busy (has an event going on)
  def is_busy?
    current_events.count.positive?
  end

  ##########################
  ### END EVENT METHODS ####
  ##########################

  ##########################
  ##### AVATAR METHODS #####
  ##########################

  # Returns a url to the avatar with the width in pixels.
  def avatar_url(size = 256)
    return "#{image_url.split('?')[0]}?sz=#{size}" if has_google_avatar? # google avatar
    return avatar.url(size <= 60 ? :thumb : :profile) if avatar.exists? # uploaded avatar

    gravatar_url(size) # default avatar
  end

  DEFAULT_GOOGLE_AVATAR_URL = "/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M".freeze

  def has_google_avatar?
    provider.present? && image_url.present? && image_url.exclude?(DEFAULT_GOOGLE_AVATAR_URL)
  end

  # Returns whether the user has a non-default avatar.
  def has_avatar?
    avatar.exists? || has_google_avatar?
  end

  ##########################
  ### END AVATAR METHODS ###
  ##########################

  ##########################
  #### FOLLOWER METHODS ####
  ##########################

  # Follows a user.
  def follow(other_user)
    if other_user.public_profile # if the other user is a public user, auto-confirm
      active_relationships.create(followed_id: other_user.id, confirmed: true)
    else
      active_relationships.create(followed_id: other_user.id)
    end
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Confirms following (let's someone follow this user)
  def confirm_follow(other_user)
    passive_relationships.find_by(follower_id: other_user.id).confirm
  end

  def deny_follow(other_user)
    passive_relationships.find_by(follower_id: other_user.id).deny
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    if following.include?(other_user) && active_relationships.find_by(followed_id: other_user.id).confirmed # if following and confirmed
      true
    else
      false
    end
  end

  # returns text indicating friendship status
  def follow_status(other_user)
    relationship = active_relationships.find_by(followed_id: other_user.id)

    return unless relationship

    if relationship.confirmed
      "confirmed"
    else
      "pending"
    end
  end

  # Fetch followers that are confirmed
  def followers
    passive_relationships.includes(:follower).where(confirmed: true).map(&:follower)
  end

  # Fetch count of followers. Doesn't eager load for optimization
  def followers_count
    passive_relationships.where(confirmed: true).size
  end

  # Fetch users being followed that are confirmed
  def following
    active_relationships.includes(:followed).where(confirmed: true).map(&:followed)
  end

  # Fetch count of following. Doesn't eager load for optimization
  def following_count
    active_relationships.where(confirmed: true).size
  end

  def followers_relationships
    passive_relationships.includes(:follower).where(confirmed: true)
  end

  def following_relationships
    active_relationships.includes(:followed).where(confirmed: true)
  end

  # returns followers of this user that the current user "knows", as in is following
  def known_followers(other_user)
    followers & other_user.followers # this finds items in both arrays
  end

  ##########################
  ### END FOLLOW METHODS ###
  ##########################

  ##########################
  ## GENERAL USER METHODS ##
  ##########################

  # destroys this user and all assocaited data
  def destroy
    categories.destroy_all # destroy all our categories
    events.destroy_all # destroy all our events as well, though cats should cover that
    notifications.destroy_all # destroy all our notifications
    active_relationships.destroy_all # destroy all following relationships
    passive_relationships.destroy_all # destroy all followed relationships
    delete # and then get rid of ourselves
  end

  def self.find_for_google_oauth2(access_token, _signed_in_resource = nil)
    data = access_token.info

    user = User.where(provider: access_token.provider, uid: access_token.uid).first

    # return if we find an Oauth user by the token and provider
    return user if user

    registered_user = User.where(email: data.email).first

    # return user with the email specified, if we find one
    return registered_user if registered_user

    User.create(name: data["name"],
                provider: access_token.provider,
                email: data["email"],
                uid: access_token.uid,
                password: Devise.friendly_token[0, 20],
                image_url: data["image"])
  end

  # Return nice text for the auth provider used by this user
  def provider_name
    if provider == "google_oauth2" # if google oauth
      "Google" # return Google
    elsif provider # if we don't recognize the provider
      provider # just return it
    end
  end

  def in_group?(group)
    groups.include?(group)
  end

  def attending_event?(event)
    EventInvite.exists? user: self,
                        host_event: event,
                        status: [:accepted, :maybe]
  end

  def invited_to_event?(event)
    EventInvite.exists?(user: self, host_event: event)
  end

  # Returns the the default category that hosted events will be placed under.
  # If a default event invite category is not set in the profile settings,
  # a new default category is automatically created.
  def event_invite_category!
    return default_event_invite_category if default_event_invite_category

    new_category = categories.create(name: "Event Invites",
                                     color: "rgb(192, 192, 192)",
                                     privacy: "private")

    # Save the new category as the default
    self.default_event_invite_category = new_category
    save!

    new_category
  end

  ##########################
  ## END GEN USER METHODS ##
  ##########################
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # Overwrite update_resource to let users to update their user without giving their password
  def update_resource(resource, params)
    if current_user.provider
      params.delete("current_password")
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  # Add new field
  private

  # Form fields allowed on sign up
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :banner, :home_time_zone)
  end

  # Form fields allowed on the edit profile page
  def account_update_params
    params.require(:user).permit(:name, :email, :public_profile, :password, :password_confirmation, :current_password,
                                 :avatar, :banner, :home_time_zone, :custom_url, :default_event_invite_category_id)
  end

  protected

  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin!, only: [:index, :promote, :demote, :inspect]
  before_action :authorize_signed_in!, only: [:destroy]

  # Get a User via params[:id] and assign to @user unless viewing multiple users
  before_action :get_user, except: [:index]

  def index
    @users = User.all.sort_by(&:name)
    @admin_tiles = true
  end

  def show
    # is this a user looking at their own profile?
    @profile = current_user == @user

    # forces custom urls to be displayed (when applicable)
    redirect_to user_path(@user), status: :moved_permanently if params[:id].is_int? && @user.has_custom_url?

    @view = params[:page]&.to_sym || :schedule
    case @view
    when :activity
      @page_view = "activity"
      @activity = @user.following_relationships + @user.followers_relationships
    when :followers
      @page_view = "follower_listing"
      @all_friends = @user.followers_relationships
    when :following
      @page_view = "following_listing"
      @following = @user.following_relationships
    when :mutual
      @page_view = "mutual_friends_listing"
      @mutual_friends = current_user.mutual_friends(@user)
    when :schedule
      @page_view = "schedule"
    end
  end

  def promote
    @user.update(admin: true)
    render json: { action: "promote", uid: @user.id, new_href: demote_user_path(@user) }
  end

  def demote
    @user.update(admin: false)
    render json: { action: "demote", uid: @user.id, new_href: promote_user_path(@user) }
  end

  # Returns the user's categories as JSON for FE JS, making sure to only show
  # categories the current_user can access
  def categories
    render json: @user.categories_accessible_by(current_user).to_json
  end

  # Returns the user's events as JSON for FE JS, making sure to only show events
  # the current_user can access
  def events
    render json: @user.events_accessible_by(current_user)
  end

  def destroy
    if current_user.admin
      @user.destroy
      redirect_to admin_panel_path, notice: "User deleted"
    elsif current_user == @user
      @user.destroy
      redirect_to home_path, notice: "Account deleted"
    else
      redirect_to user_session_path, alert: "You don't have permission to do that!"
    end
  end

  def inspect
    @user_groups = UsersGroup.where(user_id: @user.id)
  end

  protected

  def get_user
    @user = User.from_param(params[:id])
  end
end

app/views/users/_activity.html.erb
<h2 class="no-bold">Activity</h2>
<% @activity = @activity.sort_by{|f| f.created_at}.reverse %>
<% if @activity.empty? %>
  <span class="empty-text">
    <% if @profile %>
      It looks like you haven't followed anyone yet. <br> Carpe works best when enjoyed with others, so
      consider adding some connections to your profile!
    <% else %>
      It looks like <%= @user.name.split(" ")[0] %> doesn't have any connections to other users yet.
    <% end %>
  </span>
<% else %>
  <% @activity.each do |relationship| %>
    <div class="activity-listing grey-box">
      <%= link_to(relationship.other_user(@user)) do %>
        <div class="avatar float">
          <img src="<%= relationship.other_user(@user).avatar_url(50) %>" class="width-50">
        </div>
      <% end %>
      <div class="text">
        <% if @user == relationship.followed # if someone followed this user %>
          <%= @user.name %> was followed by <%= relationship.other_user(@user).name %> on <%= relationship.created_at.strftime("%b. %d, %Y") %>
        <% else # if this user followed someone %>
          <%= @user.name %> followed <%= relationship.other_user(@user).name %> on <%= relationship.created_at.strftime("%b. %d, %Y") %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<!-- Manual activity listing for joining Carpe -->
<div class="activity-listing grey-box">
  <div class="avatar float">
    <%= image_tag("pages/CarpeLetter.png", class: "carpe-logo") %>
  </div>
  <div class="text">Joined Carpe on <%= @user.created_at.strftime("%b. %d, %Y") %></div>
</div>

app/views/users/_follow_button.html.erb
<% if user == current_user %>
  <span class="friend-label">You</span>
<% else %>
  <% status = current_user.follow_status(user) %>
  <% if status == nil #not following %>
    <%= link_to "Follow", relationships_path(followed_id: user.id), class: "green button js-follow-user" %>
  <% elsif status == "confirmed" %>
    <% relationship = Relationship.where(followed_id: user.id, follower_id: current_user.id).first %>
    <%= link_to "Following", relationship_path(relationship), class: "purple button js-unfollow-user" %>
  <% elsif status == "pending" || status == "denied" %>
    <span class="friend-label">Pending</span>
  <% end %>
<% end %>

app/views/users/_follower_listing.html.erb
<h2 class="no-bold">Followers</h2>
<div id="friend-list">
  <% if @all_friends.empty? %>
    <span class="empty-text">
      <% if @profile %>
        It looks like you don't have any followers yet.
      <% else %>
        It looks like <%= @user.name.split(" ")[0] %> doesn't have any followers yet.
      <% end %>
    </span>
  <% else %>
    <%#  List followers %>
    <% for active_relationship in @all_friends %>
      <%= render "shared/user_box_horizontal", user: active_relationship.follower, relationship: active_relationship %>
    <% end %>
  <% end %>
</div>

app/views/users/_following_listing.html.erb
<h2 class="no-bold">Following</h2>
<div id="friend-list">
  <% if @following.empty? %>
    <span class="empty-text">
      <% if @profile %>
        It looks like you aren't following anyone yet.
      <% else %>
        It looks like <%= @user.name.split(" ")[0] %> isn't following anyone yet.
      <% end %>
    </span>
  <% else %>
    <%#  List users following %>
    <% for passive_relationship in @following %>
      <%= render "shared/user_box_horizontal", user: passive_relationship.followed, relationship: passive_relationship %>
    <% end %>
  <% end %>
</div>

app/views/users/_friend_button.html.erb
<% if user == current_user %>
	<span class="friend-label">You</span>
<% else %>
	<% status = current_user.follow_status(user) %>
	<% if status == nil #not friends %>
		<!--
		<%= link_to friendships_path(:friend_id => user), :method => :post, :remote => true, :class => "default green friend-button", "uid" => user.id do %>
			<span>Add Friend</span>
		<% end %>
		-->
		<%= link_to relationships_path(:followed_id => user.id), :method => :post, :remote => true, :class => "default green friend-button", "uid" => user.id do %>
			<span>Follow</span>
		<% end %>
	<% elsif status == "confirmed" %>
		<span class="friend-label">Following</span>
	<% elsif status == "pending" || status == "denied" %>
		<span class="friend-label">Pending</span>
	<% end %>
<% end %>

app/views/users/_friend_listing.html.erb
<h2 class="no-bold">Followers
	<% if current_user and !@profile %>
		<!--
		<span style="font-size: 18px;">(
			<% mut = current_user.mutual_friends(@user).count %>
			<% if mut > 0 #only link if there are some %>
				<a href="?p=mutual_friends" class="normal">	<%= mut %> Mutual </a>
			<% else %>
				<%= mut %> Shared
			<% end %>
			)
		</span>
		-->
	<% end %>
</h2>
<div id="friend-list">
<% if @all_friends.empty? %>
	<span class="empty-text">
		<% if @profile %>
			It looks like you don't have any followers yet.
		<% else %>
			It looks like <%= @user.name.split(" ")[0] %> doesn't have any followers yet.
		<% end %>
	</span>
<% else %>
	<% for active_relationship in @all_friends %>
		<!-- List followers -->
		<%= render "shared/user_box_horizontal", user: active_relationship.follower, friendship: active_relationship %>
	<% end %>
<% end%>
</div>

app/views/users/_mutual_friends_listing.html.erb
<h2 class="no-bold">Mutual Friends</h2>
<% if @mutual_friends.empty? %>
  <span class="empty-text">
    It looks like you don't have any shared connections with <%= @user.name %>!
  </span>
<% else %>
  <div id="friend-list">
    <% for user in @mutual_friends %>
      <%= render "shared/user_box_horizontal", user: user %>
    <% end %>
  </div>
<% end %>

app/views/users/_schedule.html.erb
<div class="left-align">
  Time Zone: <b><%= @user.home_time_zone %></b>
  <%= image_tag "question-circle.svg", width: 15, class: "question-tooltip", title: "This user's schedule has been automatically converted to your current local time zone." %>
</div>

<%= render "shared/schedule", user: @user %>

app/views/users/_user_box.html.erb
<div class="user-box">
	<div class="avatar">
		<a href="/u/<%= user.id %>"><img src="<%= user.user_avatar(100) %>"></a>
	</div>
	<div class="name">
		<%= user.name %><br>
		<% mut = current_user.mutual_friends(user).count %>
		<%= mut %> mutual
	</div>
	<% if user == current_user %>
		<span class="friend-label">You</span>
	<% elsif status == nil #not friends %>
		<%= link_to friendships_path(:friend_id => user), :method => :post, :class => "default green" do %>
			<span>Add Friend</span>
		<% end %>
	<% elsif status == "friend" %>
		<span class="friend-label">Friend</span>
	<% elsif status == "pending" || status == "denied" %>
		<span class="friend-label">Pending...</span>
	<% end %>
	
	<% if @show_promote %>
		<% if user.admin and user != current_user %>
			<a href="/promote?id=<%= user.id %>&de=true" class="default red">
				<span>Demote</span>
			</a>
		<% elsif user != current_user %>
			<a href="/promote?id=<%= user.id %>" class="default">
				<span>Promote</span>
			</a>
		<% end %>
	<% end %>
</div>

app/views/users/index.html.erb
<% content_for :title do %> - View Users<% end %>
<%= stylesheet_link_tag "pages/admin" %>

<div class="page-container admin-users">
  <h1 class="page-titler">
    Users
    <%= link_to_block "Admin Panel", admin_panel_url, :class=>"default" %>
  </h1>

  <% if not @users.empty? %>
    <% @users.each do |user| %>
      <%= render "shared/user_box", user: user %>
    <% end %>
  <% else %>
    <h2>There's no users but you!</h2>
  <% end %>
</div>

app/views/users/inspect.erb
<% content_for :title do %> User <%= @user.id %> Admin Overview <% end %>
<%= stylesheet_link_tag "pages/admin" %>

<div class="page-container">
  <h2 class="no-bold">Viewing Information on <%= @user.name %></h2>

  <br>
  <div class="avatar">
    <%= link_to(@user) do %>
      <%= image_tag @user.avatar_url(100) %>
    <% end %>
  </div>
  <br>

  <h2>General</h2>
  <ul class="pretty-list">
    <li><b>User id:</b> <%= @user.id %></li>
    <li><b>Email:</b> <%= @user.email %></li>
    <li><b>Account type:</b> <%= @user.admin ? 'admin' : 'user' %></li>
    <li><b>Profile type:</b> <%= @user.public_profile ? 'public' : 'private' %></li>
    <li><b>Timezone:</b> <%= @user.home_time_zone %></li>
    <!-- <li><b>Custom url:</b> <%# = @user.custom_url.blank? ? 'not using one' : @user.custom_url %></li> -->

    <li><b>Account created on:</b> <%= format_time(@user.created_at) %></li>
    <li><b>Times signed in:</b> <%= format_time(@user.sign_in_count) %></li>
    <li><b>Previous sign in:</b> <%= format_time(@user.last_sign_in_at) %> from <%= @user.last_sign_in_ip %></li>
    <li><b>Most recent sign in:</b> <%= format_time(@user.current_sign_in_at) %> from <%= @user.current_sign_in_ip %></li>

    <li><b>(Confirmed) Following:</b> <%= @user.following.count %></li>
    <li><b>(Confirmed) Follwed by:</b> <%= @user.followers.count %></li>
    <li><b>Categories created:</b> <%= @user.categories.count %></li>
    <li><b>Events created:</b> <%= @user.events.count %></li>
    <li><b>Breaks created:</b> <%= @user.repeat_exceptions.count %></li>
    <li><b>Last user object update:</b> <%= format_time(@user.updated_at) %></li>
  </ul>

  <br>
  <h2>Groups</h2>
  <% if @user.groups.empty? %>
      <p>This user is not a part of any groups yet!</p>
  <% else %>
      <ul class="pretty-list">
        <% UsersGroup.where(user_id: @user.id).each do |user_group| %>
            <li><b><%= user_group.role %></b>
              of <%= link_to(user_group.group.name, group_path(user_group.group)) %></li>
        <% end %>
      </ul>
  <% end %>
  <br>
</div>

app/views/users/search.html.erb
<% content_for :title do %> - Find People<% end %>

<div class="page-container">
  <h1 class="page-titler">Find People</h1>
  <h3 class="page-desc">
    Looking for someone? Type their name here.
    <%= form_tag("/search_users", method: "get") do %>
      <%= text_field_tag(:q, params[:q], id: "users-search-input") %>
      <%= submit_tag("Search") %>
    <% end %>
  </h3>

  <!-- TODO: Move this logic into the controller -->
  <% if @users != nil %>
    <% users = @users %>
    <h3>Showing results for "<%= params[:q] %>"</h3>
  <% else %>
    <% users = User.all %>
  <% end %>

  <% if users.size > 0 %>
    <% users.each do |user| %>
      <% if user != current_user %>
        <%= render "shared/user_box", user: user %>
      <% end %>
    <% end %>
  <% else %>
    Sorry, we didn't find any users with that name.
  <% end %>
</div>

app/views/users/show.html.erb
<% content_for :title do %> - <%= @user.name %><% end %>
<%= stylesheet_link_tag "profile" %>
<% if params[:p] == "schedule" %>
  <%= stylesheet_link_tag "schedule" %>
<% end %>

<div class="profile-header">
  <% if @user.banner.exists? # check if user specified a custom banner %>
    <div class="banner-img" style="background-image:url(<%= @user.banner.url(:desktop) %>);"></div>
  <% else %>
    <div class="banner-img"></div>
  <% end %>

  <div class="page-container">
    <div class="profile-avatar avatar">
      <%= link_to edit_user_registration_path do %>
        <% if @profile %>
          <div class="profile-overlay avatar">
            <%= image_tag "camera.svg", class: "camera-profile" %>
            <span class="upload-profile">Upload Avatar</span>
          </div>
        <% end %>
      <% end %>
      <%= image_tag @user.avatar_url %>
    </div>
    <div id="profile-text">
      <h1 id="profile-name" class="zero-top zero-bot"><a href="?"><%= @user.name %></a></h1>
      <div id="profile-follow">
        <% if current_user %>
          <%= render "follow_button", user: @user %>
        <% end %>
        <div id="profile-info">
          <% if @user.following?(current_user) %>
            Follows You
          <% end %>
        </div>
        <br>
      </div>
      <% if current_user and !@profile %>
        <div id="profile-info">
          <%= pluralize(@user.known_followers(current_user).length, "Follower") %> You Know
        </div>
      <% end %>
    </div>
    <% if @profile %>
      <%= link_to edit_user_registration_path do %>
        <div class="profile-overlay cover">
          <%= image_tag "camera.svg", class: "camera-profile" %>
          <span class="upload-profile">Upload Cover</span>
        </div>
      <% end %>
    <% end %>
    <div id="profile-buttons">
      <%= link_to user_path(@user, page: "schedule") do %>
        <div class="<%= "curr" if @view == :schedule %>">Schedule</div>
      <% end %>
      <%= link_to user_path(@user, page: "followers") do %>
        <div class="<%= "curr" if @view == :followers %>"><%= @user.followers_count %> Followers</div>
      <% end %>
      <%= link_to user_path(@user, page: "following") do %>
        <div class="<%= "curr" if @view == :following %>"><%= @user.following_count %> Following </div>
      <% end %>
      <%= link_to user_path(@user, page: "activity") do %>
        <div class="<%= "curr" if @view == :activity %>">Activity</div>
      <% end %>
    </div>
  </div>
</div>

<div class="page-container">
  <br>
  <div style="text-align: left">
  </div>

  <%= render @page_view %>
</div>