config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "users/registrations" }

  resources :users, only: [:index, :destroy, :show] do
    member do
      get "promote"
      get "demote"
      get "inspect"
      get "categories"
      get "events"
    end
  end

  # General page routes
  get "/home" => "home#index", :as => :home
  get "/userviewer" => "pages#userviewer"
  get "/about" => "pages#about"
  get "/status" => "pages#status"

  # Follow Routes
  resources :relationships

  # Group Routes
  resources :groups
  resources :user_groups, only: [:create, :update, :destroy]
  post "/invite_to_group", to: "user_groups#invite_to_group", as: :invite_to_group
  get "join_group/:id", to: "groups#join", as: :join_group
  get "leave_group/:id", to: "groups#leave", as: :leave_group

  # Admin Routes
  get "/sandbox" => "pages#sandbox"
  get "/admin" => "pages#admin", :as => :admin_panel
  post "/run_command" => "pages#run_command"
  post "/check_if_command_is_finished" => "pages#check_if_command_is_finished"

  # User Routes
  post "/deny_friend" => "friendships#deny"
  post "/confirm_friend" => "friendships#confirm"

  # Event Invite Routes
  get "/event-invite/:id/email-action/:new_status", to: "event_invites#email_action", as: :event_invite_email_action

  # Event backend commands
  resources :events, only: [:destroy] do
    post :setup_hosting, on: :member
    resources :event_invites, only: [:create], as: :invites
  end

  resources :event_invites, only: [:destroy]
  resources :categories, only: [:create, :update, :destroy]
  resources :repeat_exceptions, only: [:create, :update, :destroy]

  resource :schedule, only: [:show] do
    post :save
    get "/beta", to: "schedules#show_beta"
  end

  resources :notifications, only: [:destroy] do
    post "update(/:response)", to: "notifications#updated", as: :update, on: :member
    post :read, on: :collection
  end

  resource :search, only: [] do
    get :all, :users, :group_invitable_users
  end

  root "home#index"
end

app/views/shared/_event_tile.html.erb
  <div class="event-tile <%= "current" if event.current? %>">
  <div class="inner" style="border-color: <%= event.category.color %>">
    <div class="tile-text">
      <b><%= event.get_html_name.html_safe %></b>
      <% if event.location.present? %>
      in <%= event.location %>
      <% end %>
      <br>
      <% if event.current? #print full info about current events %>
       <%= relative_event_time_tag(event) %>
      <% else #and print start for future events %>
        <%= relative_time_tag(event.date, true) %>
      <% end %>
      <span class="toggle-details">Toggle Details</span>
    </div>
    <div class="details">
      <%= relative_time_tag(event.date, true) %> to <%= relative_time_tag(event.end_date) %>. <br>
      <% unless event.description.empty? %>
      Description: <%= event.description %>
      <% end %>
    </div>
    <div class="square" style="color: <%= event.category.color %>"><%= event.category.get_html_name.html_safe %></div>
  </div>

  <% if event.current? %>
    <div class="current-label">Going on Now</div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<%= stylesheet_link_tag "header" %>

<div class="header-main">
  <div id="menu-holder">
    <div id="header-mob-menu"><%= image_tag "menu.svg" %></div>
    <div id="mobile-menu">
      <!-- Mobile Menu Navigation -->
      <a href="/"><div>Home</div></a>
      <% if current_user %>
        <a href="/schedule"><div>My Schedule</div></a>
      <% end %>
      <a href="/about"><div>About</div></a>
      <a href="/status"><div>Status</div></a>
      <a href="https://blog.carpe.us" target="_blank">
        <div>
          Blog
        </div>
      </a>
    </div>
    <div class="carpe-font" id="header-logo">
      <a href="/"><%= image_tag "toplogo.png", :class => "carpeheader" %></a>
    </div>
  </div>
  <div class="header-text desktop">
    <!-- Desktop Menu Navigation -->
    <a href="/" class="<%= current_page?('/') ? 'active' : '' %>">Home</a>
    <% if current_user %>
      <a href="/schedule" class="<%= current_page?('/schedule') ? 'active' : '' %>">My Schedule</a>
      <a href="/groups" class="<%= current_page?('/groups') ? 'active' : '' %>">Groups</a>
    <% end %>
    <a href="/about" class="<%= current_page?('/about') ? 'active' : '' %>">About</a>
    <a href="/status" class="<%= current_page?('/status') ? 'active' : '' %>">Status</a>
    <a href="https://blog.carpe.us" target="_blank">
      Blog
      <div class="new-tab-icon"></div>
      <%= image_tag "new-tab-orange.svg", id: "new-tab-preload" %>
    </a>
    <% if current_user %>
      <br class="tablet-br">
      <%= form_tag("/search_users", method: "get", id: "users-search") do %>
        <%= text_field_tag(:q, nil, placeholder: "Search", autocomplete: "off") %>
      <% end %>
    <% end %>
  </div>
  <% if current_user %>
    <div id="user-name-panel" class="carpe-color">
      <div class="bell-hold">
        <% unless current_user.notifications.empty? %>
          <div id="num"><%= current_user.notifications.size %></div>
        <% end %>
        <%= image_tag "bellg.svg", class: "bell" %>
      </div>
      <div id="user-menu-toggler">
        <div id="user-avatar" class="avatar">
          <%= image_tag current_user.avatar_url(90) %>
        </div>
        <span class="name"><%= current_user.name.split(" ")[0] %></span>
      </div>
    </div>
  <% else %>
    <div id="user-name-panel" class="signup-links carpe-color">
      <%= link_to "Sign in", new_user_session_path %> or
      <%= link_to "Sign up", new_user_registration_path(:refer => "hdr") %>
    </div>
  <% end %>
</div>

<% if current_user %>
  <div id="user-panel" class="menu">
    <%= link_to user_path(current_user) do %>
      <div class="link">View Profile</div>
    <% end %>

    <%= link_to edit_user_registration_path do %>
      <div class="link">Edit Profile</div>
    <% end %>

    <% if current_user.admin %>
      <%= link_to admin_panel_url do %>
        <div class="link">Admin Panel</div>
      <% end %>
    <% end %>

    <%= link_to destroy_user_session_path, :method => :delete do %>
      <div class="link">Sign out</div>
    <% end %>
  </div>

  <div id="notif-panel" class="menu">
    <div id="no-notifs" <%= raw 'style="display: none"' unless current_user.notifications.empty? %>>
      You don't have any notifications right now.
    </div>

    <% current_user.notifications.group_by(&:event).each do |event, notifs| %>
      <div class="notif-title"><%= event.titleize.pluralize %></div>
      <%= render partial: "notifications/notification", collection: notifs %>
    <% end %>
  </div>
<% end %>

app/views/shared/_loading_icon.html.erb
<%# A nice loading icon, taken from https://codepen.io/aurer/pen/jEGbA %>
<% size = locals[:size] || "40px" %>
<% color = locals[:color] || "#FF6700" %>

<div class="loading-spinner">
  <svg version="1.1" id="loader-1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
  width="<%= size %>" height="<%= size %>" viewBox="0 0 50 50" style="enable-background:new 0 0 50 50;" xml:space="preserve">
    <path fill="<%= color %>" d="M25.251,6.461c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615V6.461z">
      <animateTransform attributeType="xml"
        attributeName="transform"
        type="rotate"
        from="0 25 25"
        to="360 25 25"
        dur="1.0s"
        repeatCount="indefinite" />
    </path>
  </svg>
</div>

app/views/shared/_user_adder.html.erb
<%
  # This partial takes in a name for the field, and outputs an input field that is a user adder
  # See partials/user-adder.js for the tokenInput code that handles this field

  search_path ||= "/search/all" if local_assigns[:search_path].nil?
%>

<div class="user-entry">
  <%= text_field_tag name, nil, autocomplete: "off", class: "user-adder-input",
                     data: { search_path: search_path } %>
</div>

app/views/shared/_user_box.html.erb
<div class="user-box">
  <div class="avatar">
    <%= link_to(user) do %>
      <img src="<%= user.avatar_url(100) %>">
    <% end %>
  </div>

  <div class="name">
    <%= user.name %>
  </div>

  <% if @admin_tiles %>
    <!-- Show promotion and demotion admin buttons -->
    <div class="promotion">
      <% if user.admin and user != current_user %>
        <%= link_to_block "Demote", demote_user_path(user), :class => "default red", :remote => true, "uid" => user.id %>
      <% elsif user != current_user %>
        <%= link_to_block "Promote", promote_user_path(user), :class => "default", :remote => true, "uid" => user.id %>
      <% end %>
    </div>
    <%= link_to_block "Delete", user_path(user), :method => :delete, data: { confirm: 'Are you sure?' }, :class => "default red" %>
    <%= link_to_block "Info", inspect_user_path(user), :class => "default green" %>
  <% else %>
    <% if current_user.present? %>
      <%= render "/users/follow_button", user: user %>
    <% end %>
  <% end %>

  <% if @group %>
    <% if user.in_group? @group %>
      <a href="?uid=<%= user.id %>&del=t" class="default red">
        <span>Remove</span>
      </a>
    <% else %>
      <a href="?uid=<%= user.id %>" class="default">
        <span>Add</span>
      </a>
    <% end %>
  <% end %>
</div>

app/views/shared/_user_box_horizontal.html.erb
<% if @home # make the whole tile link if on home %>
  <a href="<%= user_path(user) %>">
<% end %>
  <div class="user-listing grey-box <%= @profile ? "profile" : "" %>">
    <% unless @home # don't make avatar link if on home %>
      <a href="<%= user_path(user) %>">
    <% end %>
      <div class="avatar">
        <% if @home %>
          <%= image_tag user.avatar_url(60), class: "width-60" %>
        <% else %>
          <%= image_tag user.avatar_url(100) %>
        <% end %>
      </div>
    <% unless @home %>
      </a>
    <% end %>

    <div class="user-details">

      <span class="user-name"><%= user.name %></span><br>
      <% if @profile %>
        Following since: <%= relationship.created_at.strftime("%b. %d, %Y") %> <br>

        <% if current_user == relationship.follower # if the current user is following this person, let them unfollow %>
          <%= link_to "Unfollow", relationship_path(relationship), class: "red button js-unfollow-user" %>
        <% else %>
          <%= link_to "Remove", relationship_path(relationship), class: "red button js-unfollow-user" %>
        <% end %>
      <% elsif current_user %>
        <% if !@home %>
          <span id="mutual-friends"><%= user.followers.length %> followers</span>
          <br>
          <%= render "/users/follow_button", user: user %>
        <% else %>
          <% if user.is_busy? %>
            <div class="red circle"></div>
            <% if user.current_events[0].accessible_by?(current_user) %>
              <% event_name = user.current_events[0].get_html_name.html_safe %>
              <span class="carpe-color"><%= event_name %></span>
            <% else %>
              Busy
            <% end %>
            until <%= relative_time_tag(user.current_events[0].end_date) %>
          <% else %>
            <% next_event = user.next_event %>
            <div class="green circle"></div>
            <% if next_event %>
              Free until <%= relative_time_tag(next_event.date) %>
            <% else %>
              Free the rest of the day
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% if @home %>
  </a>
<% end %>